support for encoding to oc protos and exporting to agent
opencensus-beam/opencensus_service pull request #1
Opened 2019-02-08 00:00 UTC by tsloughter

This needs to wait for a new grpcbox which I'll cut once a new gpb is released. But the actual code for review is ready for reviewing.

2019-02-08 00:48 UTC, hauleth requested changes

2019-02-08 00:48 UTC, hauleth commented on .circleci/config.yml
> +            - rebar3/compile
I think we should also check if the generated proto modules are up to date.

2019-02-08 00:48 UTC, hauleth commented on src/oc_reporter_service.erl
> +    application:ensure_all_started(opencensus_service).
Shouldn't we check on return value here?

2019-02-08 00:48 UTC, hauleth commented on src/oc_reporter_client.erl
> +    gen_statem:start_link({local, ?MODULE}, ?MODULE, [], []).
What in case when user wants to send to N different gRPC upstreams? Is such configuration supported?

2019-02-08 00:48 UTC, hauleth commented on test/opencensus_service_SUITE.erl
> +    ok.
As `*_per_testcase/2` callback are optional is there any sense in implementing them as trivial passthroughs?

2019-02-08 00:48 UTC, hauleth commented on test/opencensus_service_SUITE.erl
> +                 end_time={-576460679697900156, 2091207418848923700}},
Maybe it would be worth to property test this exporter?

2019-02-08 00:48 UTC, hauleth commented on src/oc_reporter_service.erl
> +                    end, {[], 0, 0}, TimeEvents),
This is pretty big nested callback, maybe it would be worth moving it to separate function.

2019-02-08 00:48 UTC, hauleth commented on src/oc_reporter_service.erl
> +      %% source_version => undefined
Testing leftovers or unimplemented features?

2019-02-08 00:48 UTC, hauleth commented on src/oc_reporter_client.erl
> +            {keep_state, Data#data{stream=undefined}}
Maybe we should log error or at least warning here, not just munch the error and do nothing.

2019-02-08 02:52 UTC, tsloughter commented on src/oc_reporter_service.erl
> +      %% source_version => undefined
Unimplemented. Not sure what they should actually be yet.

2019-02-08 02:53 UTC, tsloughter commented on src/oc_reporter_client.erl
> +            {keep_state, Data#data{stream=undefined}}
Yea, I'll add a debug log for now. Meant to bring up in the channel that we need to talk about retries and what the reporter should do about a reporter failing, if anything.

2019-02-08 02:54 UTC, tsloughter commented on src/oc_reporter_client.erl
> +    gen_statem:start_link({local, ?MODULE}, ?MODULE, [], []).
It isn't. This is for sending to the single oc-agent, not like a generic grpc reporter.

2019-02-08 02:56 UTC, tsloughter commented on src/oc_reporter_service.erl
> +    application:ensure_all_started(opencensus_service).
Probably not necessary. It'll be started by the release and fail there and be handled.

2019-02-08 02:59 UTC, tsloughter commented on src/oc_reporter_service.erl
> +                    end, {[], 0, 0}, TimeEvents),
It is just two clauses, but yea, I'll break it out to `to_std_time_event`.

2019-02-08 03:06 UTC, tsloughter commented on test/opencensus_service_SUITE.erl
> +    ok.
Na, just there from copy/paste and usually end up using them as I expand a test suite.

2019-02-08 03:11 UTC, tsloughter commented on src/oc_reporter_service.erl
> +      %% source_version => undefined
I guess `build_id` could be the beam module checksum... `source_version` would end up being the same I think, since rare that anyone puts a `vsn` attribute in their modules.

2019-02-08 08:57 UTC, hauleth commented on src/oc_reporter_service.erl
> +    application:ensure_all_started(opencensus_service).
Then I would not try to launch it again in `init/1`. instead just let it fail if someone didn't configured it properly.

2019-02-08 08:59 UTC, hauleth commented on src/oc_reporter_client.erl
> +    gen_statem:start_link({local, ?MODULE}, ?MODULE, [], []).
It can be quite confusing when (and if) census-instrumenatation/opencensus-erlang#130 will be merged or if we decide to adopt census-instrumenatation/opencensus-erlang#133.

2019-02-08 09:02 UTC, hauleth commented on src/oc_reporter_service.erl
> +      %% source_version => undefined
I would go with `application:get_key(App, vsn)` instead of module checksum, at least for `source_version`.

2019-02-08 15:17 UTC, tsloughter commented on src/oc_reporter_service.erl
> +      %% source_version => undefined
Hm, yea, I was thinking it meant the module version, now I'm not sure.

And we'd need to track what application a module is in, I don't think there is an efficient way to check that, maybe there is.

2019-02-08 15:19 UTC, hauleth commented on src/oc_reporter_service.erl
> +      %% source_version => undefined
Fetch it from application env and force user to set it. This is how it is often done (at least in Elixir world).

2019-02-08 15:39 UTC, tsloughter commented on src/oc_reporter_service.erl
> +    application:ensure_all_started(opencensus_service).
Eh, why make it more complicated and potentially confusing. If there was a builtin way to set these sorts of dynamic dependencies I'd agree.

2019-02-08 15:42 UTC, tsloughter commented on src/oc_reporter_client.erl
> +    gen_statem:start_link({local, ?MODULE}, ?MODULE, [], []).
Note that there aren't any arguments to the reporter. I think if it took arguments for what address to connect to that this confusion would be an issue, but it is clearly an application/reporter for talking solely to the ocagent configured by the application environment.

2019-02-08 21:26 UTC, tsloughter commented on test/opencensus_service_SUITE.erl
> +                 end_time={-576460679697900156, 2091207418848923700}},
Yea, probably all of them could benefit from that.

2019-02-08 21:28 UTC, tsloughter commented
I've updated the grpcbox dep so think this is ready to go except for a few outstanding review discussions.

2019-02-08 22:53 UTC, tsloughter commented on src/oc_reporter_service.erl
> +      %% source_version => undefined
@hauleth not sure what you are referring to for getting from the application env and having a user set.

2019-02-08 22:56 UTC, hauleth commented on src/oc_reporter_service.erl
> +      %% source_version => undefined
@tsloughter in `sys.config` either use:

```erlang
{opencensus, [
  {client, [{application, my_app}]}]}
```

Or

```erlang
{opencensus, [
  {reporters, [{oc_reporter_service, [{application, my_app}]}]}]}
```

2019-02-08 22:57 UTC, hauleth commented on config/example.config
> + {grpcbox, [{client, #{channels => [{default_channel, [{http, "localhost", 55678, []}], #{}}]}}]}
Why use `grpcbox` application for configuring `opencensus` reporter? It should be configured under `opencensus` application.

2019-02-08 22:58 UTC, tsloughter commented on src/oc_reporter_service.erl
> +      %% source_version => undefined
Ah. But this is for each frame in a stack trace, it will contain modules from multiple applications.

2019-02-08 22:59 UTC, tsloughter commented on config/example.config
> + {grpcbox, [{client, #{channels => [{default_channel, [{http, "localhost", 55678, []}], #{}}]}}]}
It isn't using the grpcbox application, it is uses `opencensus_service` application environment to configure, see `opencensus_service_sup`

2019-02-08 23:00 UTC, tsloughter commented on config/example.config
> + {grpcbox, [{client, #{channels => [{default_channel, [{http, "localhost", 55678, []}], #{}}]}}]}
Ohh, thought this was a comment about the multiple endpoints :), yea, this is a mistake in the example.config, fixing.

2019-02-08 23:02 UTC, hauleth commented on src/oc_reporter_service.erl
> +      %% source_version => undefined
Even if so, the version should be bound to user root application, not to application that issued the span. Otherwise we would need to spawn one OpenCensus instance per application to track all relations between applications as well. Remember that Erlang application is something different from the "application" used by all other OpenCensus libraries.

2019-02-08 23:04 UTC, tsloughter commented on src/oc_reporter_service.erl
> +      %% source_version => undefined
The source version here should be for whatever source the frame of the stacktrace relates to. If it was meant to be a source version that relates to a root application it wouldn't be in each frame.

2019-02-08 23:05 UTC, hauleth commented on config/example.config
> + {grpcbox, [{client, #{channels => [{default_channel, [{http, "localhost", 55678, []}], #{}}]}}]}
However as I said, I would allow multiple `oc_reporter_service` and each of them should have passed variables as an options. For me it makes a lot of sense in situations when, for example, some external service decide to be OpenCensus compatible and fetch data directly via gRPC instead of "going through" other protocol like statsd or graphite.

2019-02-08 23:09 UTC, hauleth commented on src/oc_reporter_service.erl
> +      %% source_version => undefined
AFAIK there is no way to know which application given module belongs to. If there is a way, then we could utilise that. Alternative solution is to allow setting that value in the config to release version, because this is what I believe was the "original meaning" in OpenCensus specification.

2019-02-08 23:20 UTC, tsloughter commented on config/example.config
> + {grpcbox, [{client, #{channels => [{default_channel, [{http, "localhost", 55678, []}], #{}}]}}]}
Nothing is stopping that from happening, they just wouldn't use the reporter that is specifically for talking to the opencensus agent.

Though it is also just a bad idea... should want to get shit out of your app as fast as possible and let something else, like the agent, handle the rest. Also why a sequence of reporter doesn't make much sense. Obviously there are times the added complexity of having to run an agent isn't worth it so we do need reporters besides the agent one, but when you start getting into sending to multiple reporters you are likely in a place that it is worth it to use the agent.

But since there isn't extra overhead to just requiring an optional atom name be passed to the reporter if you want to start more than 1 and make the supervisor a simple one for one I'll do that really quick.

2019-02-08 23:49 UTC, tsloughter commented on src/oc_reporter_service.erl
> +      %% source_version => undefined
Right, that is what I said earlier. Lets just leave them undefined for the time being, the docs on the proto can barely even describe what they are.

2019-02-08 23:49 UTC, tsloughter commented on src/oc_reporter_client.erl
> +    gen_statem:start_link({local, ?MODULE}, ?MODULE, [], []).
Updated.

2019-02-10 21:39 UTC, tsloughter commented
@hauleth @deadtrickster this ok to merge? Can always make changes on top of it later.

2019-02-10 21:48 UTC, deadtrickster approved these changes

2019-02-10 22:00 UTC, merged

2019-02-11 16:23 UTC, hauleth commented on src/oc_reporter_service.erl
> +      %% source_version => undefined
@tsloughter if we would add `application:get_application/0` return value to the metadata by default (and this would need to be done by default) then we could handle that.