Document installation and configuration for Elixir
opencensus-beam/opencensus_service pull request #2
Opened 2019-05-14 23:20 UTC by garthk

After the thrash in `#opencensus`, figured the least I could do was save the next Elixir user the trouble.

2019-05-14 23:27 UTC, tsloughter requested changes

2019-05-14 23:27 UTC, tsloughter commented on README.md
> +    {reporter, {oc_reporter_service, #{}}
```suggestion
    {reporters, [{oc_reporter_service, #{}}]}
```

2019-05-17 04:34 UTC, garthk commented on README.md
> +    {reporter, {oc_reporter_service, #{}}
I accepted your changes, but GitHub thinks otherwise since I squashed. Sigh.

2019-05-18 17:24 UTC, tsloughter approved these changes

2019-05-18 17:25 UTC, merged